### ISSUE TITLE
Unable to add or remove anyone from lists. No context menu

### ISSUE THREAD

**Issue by thakyZ** [Bricklou/powercord-pindms#14]
```js
Uncaught (in promise) TypeError: Cannot read property 'default' of null
    at _injectPeopleList (\powercord\src\Powercord\plugins\powercord-pindms\modules\FriendsList.js:212:32)
VM1477 \powercord\src\Powercord\plugins\powercord-pindms\modules\ContextMenuGroup.js:131 Uncaught (in promise)
```   
```js
TypeError: Cannot read property 'default' of null
    at PinDMs.module.exports \powercord\src\Powercord\plugins\powercord-pindms\modules\ContextMenuGroup.js:131:7)
VM1478 \powercord\src\Powercord\plugins\powercord-pindms\modules\ContextMenuUser.js:134 Uncaught (in promise)
```   
```js
TypeError: Cannot read property 'default' of null
    at PinDMs.module.exports (\powercord\src\Powercord\plugins\powercord-pindms\modules\ContextMenuUser.js:134:7)
```   
No context menus show up when right clicking on a DM to add them or remove them from a list

**Comment by Bricklou** [comment]
It's related to what I explained in #13

**Comment by thakyZ** [comment]
Yea, sorry, let me add these errors to that one. I just now noticed it. Honestly, I didn't think that use would be related to mine.
